# coding: utf-8

"""
    Ducksms

    The version of the OpenAPI document: 1.0.0
    Contact: support@ducksms.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ducksms_api
from ducksms_api.api.sender_id_api import SenderIDApi  # noqa: E501
from ducksms_api.rest import ApiException


class TestSenderIDApi(unittest.TestCase):
    """SenderIDApi unit test stubs"""

    def setUp(self):
        self.api = ducksms_api.api.sender_id_api.SenderIDApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_sender(self):
        """Test case for create_sender

        Create a Sender ID  # noqa: E501
        """
        pass

    def test_delete_sender(self):
        """Test case for delete_sender

        Delete a Sender ID  # noqa: E501
        """
        pass

    def test_get_sender(self):
        """Test case for get_sender

        Get a single Sender ID  # noqa: E501
        """
        pass

    def test_list_sender(self):
        """Test case for list_sender

        List Sender ID  # noqa: E501
        """
        pass

    def test_update_sender(self):
        """Test case for update_sender

        Update a Sender ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
