# coding: utf-8

"""
    Ducksms

    The version of the OpenAPI document: 1.0.0
    Contact: support@ducksms.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ducksms_api
from ducksms_api.models.credit_history import CreditHistory  # noqa: E501
from ducksms_api.rest import ApiException

class TestCreditHistory(unittest.TestCase):
    """CreditHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreditHistory
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ducksms_api.models.credit_history.CreditHistory()  # noqa: E501
        if include_optional :
            return CreditHistory(
                status = 200, 
                message = 'Credit history data return successfully', 
                data = [{"txid":"342660487","type":"charge","amount":1,"description":"SMS credit charge","smsid":"1201910908"},{"txid":"1220368389","type":"charge","amount":2,"description":"SMS credit charge","smsid":"634967613"}]
            )
        else :
            return CreditHistory(
        )

    def testCreditHistory(self):
        """Test CreditHistory"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
