# coding: utf-8

"""
    Ducksms

    The version of the OpenAPI document: 1.0.0
    Contact: support@ducksms.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ducksms_api
from ducksms_api.models.created_sms_send import CreatedSmsSend  # noqa: E501
from ducksms_api.rest import ApiException

class TestCreatedSmsSend(unittest.TestCase):
    """CreatedSmsSend unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreatedSmsSend
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ducksms_api.models.created_sms_send.CreatedSmsSend()  # noqa: E501
        if include_optional :
            return CreatedSmsSend(
                status = 201, 
                message = 'The sms message is successfully scheduled', 
                data = {"smsid":"5006623151","scheduled_at":false,"sender_id":{"name":"DUCKSMS"},"mobile_number":[{"number":"60131234567","msgid":2006553122},{"number":"60131234562","msgid":7006553121}],"credit":{"charge_per_sms":1,"charge_per_number":1,"charge":1,"balance":986762,"after":986761},"message":{"type":"ascii","total":1,"length":31,"message":"RM0 DUCKSMS: Hello World, Good morning!"},"callback_url":"https://webhook.site/2a88e4b4-56f7-46ee-b3a4-2f05d8b8456e","contains_special_characters":false}
            )
        else :
            return CreatedSmsSend(
        )

    def testCreatedSmsSend(self):
        """Test CreatedSmsSend"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
