# coding: utf-8

"""
    Ducksms

    The version of the OpenAPI document: 1.0.0
    Contact: support@ducksms.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ducksms_api
from ducksms_api.api.sms_schedule_api import SmsScheduleApi  # noqa: E501
from ducksms_api.rest import ApiException


class TestSmsScheduleApi(unittest.TestCase):
    """SmsScheduleApi unit test stubs"""

    def setUp(self):
        self.api = ducksms_api.api.sms_schedule_api.SmsScheduleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_sms_schedule(self):
        """Test case for cancel_sms_schedule

        Cancel Sms Schedule  # noqa: E501
        """
        pass

    def test_list_sms_schedule(self):
        """Test case for list_sms_schedule

        List Sms Schedule  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
