# coding: utf-8

"""
    Ducksms

    The version of the OpenAPI document: 1.0.0
    Contact: support@ducksms.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ducksms_api
from ducksms_api.models.list_sms_schedule import ListSmsSchedule  # noqa: E501
from ducksms_api.rest import ApiException

class TestListSmsSchedule(unittest.TestCase):
    """ListSmsSchedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ListSmsSchedule
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ducksms_api.models.list_sms_schedule.ListSmsSchedule()  # noqa: E501
        if include_optional :
            return ListSmsSchedule(
                status = 200, 
                message = 'The sms scheduled return successfully', 
                data = [{"smsid":"59961854","type":"quick","scheduled_at":"2022-12-04 13:41:00","sender_name":"DUCKSMS","message":"Hello World","recipients":1,"status":"completed","created_at":"2022-12-03 13:40:30","updated_at":"2022-12-03 13:46:20"},{"smsid":"1636438975","type":"quick","scheduled_at":"2022-12-03 12:34:00","sender_name":"MYCOMPANY","message":"Hi john","recipients":1,"status":"cancelled","created_at":"2022-12-03 12:32:42","updated_at":"2022-12-03 12:32:46"}]
            )
        else :
            return ListSmsSchedule(
        )

    def testListSmsSchedule(self):
        """Test ListSmsSchedule"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
