# coding: utf-8

"""
    Ducksms

    The version of the OpenAPI document: 1.0.0
    Contact: support@ducksms.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ducksms_api
from ducksms_api.models.list_sender import ListSender  # noqa: E501
from ducksms_api.rest import ApiException

class TestListSender(unittest.TestCase):
    """ListSender unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ListSender
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ducksms_api.models.list_sender.ListSender()  # noqa: E501
        if include_optional :
            return ListSender(
                status = 200, 
                message = 'Senders data return successfully', 
                data = [{"id":1,"name":"DUCKSMS","description":"Example sender id description","default":true,"status":"active","created_at":"2022-11-29T03:28:39.000000Z","updated_at":"2022-11-29T03:28:39.000000Z"},{"id":2,"name":"MYCOMPANY","description":"Example sender id description","default":false,"status":"inactive","created_at":"2022-11-30T03:28:39.000000Z","updated_at":"2022-11-30T03:28:39.000000Z"}]
            )
        else :
            return ListSender(
        )

    def testListSender(self):
        """Test ListSender"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
